baseURL: "https://foopi.top"
languageCode: en-us
title: Foo's

theme: PaperMod

# paginate: 5

buildDrafts: true
buildFuture: false
buildExpired: false

enableRobotsTXT: true

cleanDestinationDir: true

params:
  # # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Foo
    subtitle: "Never Too Late."
    imageUrl: "https://img.foopi.top/img/avatar.webp"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Foo
    buttons:
      - name: Posts
        url: posts
      - name: 100DaysOfSwiftUI
        url: 100daysofswiftui
      - name: Previous
        url: "https://blog.foopi.top/"

  socialIcons:
    - name: github
      url: "https://github.com/Haok7"
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"

  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  showtoc: true

  disableScrollToTop: false

  cover:
    linkFullImages: true

  assets:
    disableHLJS: true
    disableFingerprinting: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    # - identifier: previous
    #   name: previous
    #   url: https://blog.foopi.top
    #   weight: 40

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    style: monokai
    ## The following options may cause code blocks to display exceptionally on mobile devices.
    # lineNos: true
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true